### ISSUE TITLE
[bug] No test result displayed

### ISSUE THREAD

**Issue by pinghe** [Raathigesh/majestic#157]
## Version Info

- Version of Majestic: 1.6.0
- Version of Jest: 24.8.0
- Version of Node: v12.2.0
- Operating System: ubuntu 
- Version of node-fetch: 2.6.0

```
yarn run v1.16.0
$ majestic
⚡  Majestic v1.6.0 is running at http://localhost:4000
(node:6937) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:4000/test-start failed, reason: Parse Error
    at ClientRequest.<anonymous> (/myprj/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:196:13)
    at Socket.socketOnData (_http_client.js:465:9)
    at Socket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
(node:6937) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6937) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Raathigesh** [comment]
Could you please provide an example repository where this issue is reproducible?
