### ISSUE TITLE
Linux Debian / Ubuntu support

### ISSUE THREAD

**Issue by guyellis** [Raathigesh/majestic#39]
## Feature request

Please can you provide a .deb install file for Linux Debian (includes Ubuntu) distros.

## Version Info

n/a

**Comment by Raathigesh** [comment]
I have to find a way to set up the environment so I can test and release. I'll try to set up a VM for this. Would you be able to help with testing this in a Linux environment? Checking out a repo and running the app to make things are working as it supposes to would be helpful.

**Comment by James-E-Adams** [comment]
If the ubuntu image ever downloads, will see what I can do - might have to wait till later in the week though.

**Comment by Raathigesh** [comment]
Thanks @James

**Comment by James-E-Adams** [comment]
![image](https://user-images.githubusercontent.com/9067274/34646452-cabc2fbe-f3bc-11e7-9944-8cf19b94749d.png)
It's not looking promising.

**Comment by guyellis** [comment]
I can definitely help test this if there's a .deb file to download.

**Comment by Raathigesh** [comment]
We don't have a .deb file yet. But you could clone the repo and then do the following to get it running.
```
yarn install
yarn dev
```

if you see the app running successfully, try `yarn linux`. This command would create a package.

**Comment by guyellis** [comment]
This is what I get when I run it on Ubuntu 16.04:
```bash
  Error: Error: ENOENT, dev-app-update.yml not found in /home/guy/source/majestic/node_modules/electron/dist/resources/default_app.asar
      at notFoundError (ELECTRON_ASAR.js:115:19)
      at fs.readFile (ELECTRON_ASAR.js:478:16)
      at go$readFile (/home/guy/source/majestic/node_modules/graceful-fs/graceful-fs.js:73:14)
      at readFile (/home/guy/source/majestic/node_modules/graceful-fs/graceful-fs.js:70:12)
      at readFile (/home/guy/source/majestic/node_modules/universalify/index.js:5:67)
      at /home/guy/source/majestic/node_modules/electron-updater/src/AppUpdater.ts:334:27
      at Generator.next (<anonymous>)
      at AppImageUpdater.loadUpdateConfig (/home/guy/source/majestic/node_modules/electron-updater/out/AppUpdater.js:368:11)
      at Lazy.AppUpdater.configOnDisk.Lazy (/home/guy/source/majestic/node_modules/electron-updater/src/AppUpdater.ts:98:43)
  From previous event:
      at /home/guy/source/majestic/node_modules/electron-updater/src/AppUpdater.ts:334:27
      at Generator.next (<anonymous>)
  From previous event:
      at AppImageUpdater.loadUpdateConfig (/home/guy/source/majestic/node_modules/electron-updater/out/AppUpdater.js:368:11)
      at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/home/guy/source/majestic/node_modules/electron-updater/src/AppUpdater.ts:98:43)
      at Lazy.get value [as value] (/home/guy/source/majestic/node_modules/lazy-val/src/main.ts:18:23)
      at /home/guy/source/majestic/node_modules/electron-updater/src/AppUpdater.ts:245:33
      at Generator.next (<anonymous>)
  From previous event:
      at AppImageUpdater.doCheckForUpdates (/home/guy/source/majestic/node_modules/electron-updater/out/AppUpdater.js:326:11)
      at /home/guy/source/majestic/node_modules/electron-updater/src/AppUpdater.ts:228:25
      at Generator.next (<anonymous>)
      at runCallback (timers.js:672:20)
      at tryOnImmediate (timers.js:645:5)
      at processImmediate [as _immediateCallback] (timers.js:617:5)
  From previous event:
      at AppImageUpdater._checkForUpdates (/home/guy/source/majestic/node_modules/electron-updater/out/AppUpdater.js:280:11)
      at AppImageUpdater.checkForUpdates (/home/guy/source/majestic/node_modules/electron-updater/src/AppUpdater.ts:177:35)
      at callFunction (/home/guy/source/majestic/node_modules/electron/dist/resources/electron.asar/browser/rpc-server.js:249:18)
      at EventEmitter.<anonymous> (/home/guy/source/majestic/node_modules/electron/dist/resources/electron.asar/browser/rpc-server.js:357:5)
      at emitMany (events.js:127:13)
      at EventEmitter.emit (events.js:204:7)
      at WebContents.<anonymous> (/home/guy/source/majestic/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:256:13)
      at emitTwo (events.js:106:13)
      at WebContents.emit (events.js:194:7)
```

**Comment by Raathigesh** [comment]
Thank you for getting back on this. You can safely ignore this warning. This is the auto updater complaining while we start the app in dev mode.

Other than this,  did you see the UI and is the app functional?

**Comment by guyellis** [comment]
This is the repo I'm working on: https://github.com/guyellis/plant

This is the commit that adds the reference to the jest custom config: https://github.com/guyellis/plant/commit/60c9cf8386b42fc0c6743b598ab9aefff5c79ec0

This is the error that I get when I try File > Open Project:

```
home/guy/source/majestic/node_modules/jest-editor-support/build/parsers/babylon_parser.js:65 Uncaught TypeError: Cannot read property 'type' of null
    at isFunctionCall (/home/guy/source/majestic/node_modules/jest-editor-support/build/parsers/babylon_parser.js:65:11)
    at getNameForNode (/home/guy/source/majestic/node_modules/jest-editor-support/build/parsers/babylon_parser.js:81:10)
    at isAnIt (/home/guy/source/majestic/node_modules/jest-editor-support/build/parsers/babylon_parser.js:103:18)
    at searchNodes (/home/guy/source/majestic/node_modules/jest-editor-support/build/parsers/babylon_parser.js:135:11)
    at element.expression.arguments.filter.forEach.argument (/home/guy/source/majestic/node_modules/jest-editor-support/build/parsers/babylon_parser.js:167:29)
    at Array.forEach (native)
    at searchNodes (/home/guy/source/majestic/node_modules/jest-editor-support/build/parsers/babylon_parser.js:167:9)
    at exports.parse.file (/home/guy/source/majestic/node_modules/jest-editor-support/build/parsers/babylon_parser.js:172:3)
    at TreeNode.parseItBlocks (webpack-internal:///./src/renderer/stores/TreeNode.ts:76:24)
    at executeAction (/home/guy/source/majestic/node_modules/mobx/lib/mobx.js:915:19)
```

The Coverage "viewer", however, is working well and I really like that interface into my coverage files - so that you for that!

**Comment by mpourismaiel** [comment]
I tried `yarn dev` and didn't any visual problems. Although `yarn linux` yielded this error:

```
> majestic@0.1.0 compile /home/mahdi/.bin/majestic/app
> electron-webpack

[1] Hash: 54a9acafdc7cb629eebeae9e4acd380adba557b8                                         
Version: webpack 3.8.1
Child
    Hash: 54a9acafdc7cb629eebe
    Time: 5929ms
     2 assets
       [1] multi ./src/main/index.ts 28 bytes {0} [built]
       [2] ./src/main/index.ts + 2 modules 6.48 kB {0} [built]
        + 3 hidden modules
    
    ERROR in /home/mahdi/.bin/majestic/app/src/renderer/components/test-file/it-block.tsx
    [tsl] ERROR in /home/mahdi/.bin/majestic/app/src/renderer/components/test-file/it-block.tsx(7,31)
          TS2307: Cannot find module '../../types/it-block'.
    
    ERROR in /home/mahdi/.bin/majestic/app/src/renderer/components/fail-summary/fail-summary.tsx
    [tsl] ERROR in /home/mahdi/.bin/majestic/app/src/renderer/components/fail-summary/fail-summary.tsx(29,17)
          TS2605: JSX element type 'ItBlockWithStatus' is not a constructor function for JSX elements.
      Property 'render' is missing in type 'ItBlockWithStatus'.
    
    ERROR in /home/mahdi/.bin/majestic/app/src/renderer/components/fail-summary/fail-summary.tsx
    [tsl] ERROR in /home/mahdi/.bin/majestic/app/src/renderer/components/fail-summary/fail-summary.tsx(29,17)
          TS2607: JSX element class does not support attributes because it does not have a 'props' property.
Child
    Hash: ae9e4acd380adba557b8
    Time: 13633ms
     11 assets
       [5] ./src/renderer/util/workspace.ts 3.77 kB {0} [built]
      [11] ./src/renderer/util/jest.ts 3.69 kB {0} [built]
      [16] multi ./src/renderer/index.ts 28 bytes {0} [built]
      [17] ./src/renderer/index.ts + 40 modules 75.6 kB {0} [built]
      [20] ./src/renderer/stores/Runner.ts 10.8 kB {0} [built]
      [22] ./src/renderer/util/Process.ts 2.97 kB {0} [built]
      [26] ./src/renderer/stores/WatcherDetails.ts 803 bytes {0} [built]
      [39] (webpack)/buildin/module.js 495 bytes {0} [built]
      [50] ./src/renderer/assets/logo.png 67 bytes {0} [built]
      [58] ./src/renderer/style.css 41 bytes {0} [built]
      [69] ./node_modules/css-loader!./src/renderer/style.css 1.82 kB [built]
        + 59 hidden modules
    
    ERROR in ./src/renderer/components/test-file/it-block.tsx
    [tsl] ERROR in /home/mahdi/.bin/majestic/app/src/renderer/components/test-file/it-block.tsx(7,31)
          TS2307: Cannot find module '../../types/it-block'.
    
    ERROR in ./src/renderer/components/fail-summary/fail-summary.tsx
    [tsl] ERROR in /home/mahdi/.bin/majestic/app/src/renderer/components/fail-summary/fail-summary.tsx(29,17)
          TS2605: JSX element type 'ItBlockWithStatus' is not a constructor function for JSX elements.
      Property 'render' is missing in type 'ItBlockWithStatus'.
    
    ERROR in ./src/renderer/components/fail-summary/fail-summary.tsx
    [tsl] ERROR in /home/mahdi/.bin/majestic/app/src/renderer/components/fail-summary/fail-summary.tsx(29,17)
          TS2607: JSX element class does not support attributes because it does not have a 'props' property.
    
    ERROR in ./src/renderer/components/fail-summary/fail-summary.tsx
    Module build failed: Error: Typescript emitted no output for /home/mahdi/.bin/majestic/app/src/renderer/components/fail-summary/fail-summary.tsx.
        at successLoader (/home/mahdi/.bin/majestic/app/node_modules/ts-loader/dist/index.js:47:15)
        at Object.loader (/home/mahdi/.bin/majestic/app/node_modules/ts-loader/dist/index.js:29:12)
     @ ./src/renderer/components/content.tsx 8:0-54
     @ ./src/renderer/Container.tsx
     @ ./src/renderer/app.tsx
     @ ./src/renderer/index.ts
     @ multi ./src/renderer/index.ts
    
    ERROR in ./src/renderer/components/test-file/it-block.tsx
    Module build failed: Error: Typescript emitted no output for /home/mahdi/.bin/majestic/app/src/renderer/components/test-file/it-block.tsx.
        at successLoader (/home/mahdi/.bin/majestic/app/node_modules/ts-loader/dist/index.js:47:15)
        at Object.loader (/home/mahdi/.bin/majestic/app/node_modules/ts-loader/dist/index.js:29:12)
     @ ./src/renderer/components/test-file/test-file-content.tsx 2:0-28
     @ ./src/renderer/components/content.tsx
     @ ./src/renderer/Container.tsx
     @ ./src/renderer/app.tsx
     @ ./src/renderer/index.ts
     @ multi ./src/renderer/index.ts
    Child html-webpack-plugin for "index.html":
         1 asset
           [0] ./node_modules/html-loader?minimize=false!/__virtual__/renderer-index.html 278 bytes {0} [built]
    Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!src/renderer/style.css:
           [0] ./node_modules/css-loader!./src/renderer/style.css 1.82 kB {0} [built]
            + 1 hidden module
    Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/@blueprintjs/core/dist/blueprint.css:
         6 assets
           8 modules

npm ERR! Linux 4.13.0-21-generic
npm ERR! argv "/home/mahdi/.nvm/versions/node/v7.8.0/bin/node" "/home/mahdi/.nvm/versions/node/v7.8.0/bin/npm" "run" "compile"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! majestic@0.1.0 compile: `electron-webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the majestic@0.1.0 compile script 'electron-webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the majestic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs majestic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls majestic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mahdi/.npm/_logs/2018-01-09T13_31_29_360Z-debug.log
error Command failed with exit code 2.
```

**Comment by klequis** [comment]
Also gave it a try on Ubuntu 16.04 using `yarn dev`. Ignoring the error in the console, same as @guyellis , it appears to be working on a simple JS project with one test file and 11 tests.

**Comment by Raathigesh** [comment]
Hi Everyone,

Majestic now ships as a npm module so it should work in linux without any additional effort. If someone could test it and see how it goes, it would be lovely. The instruction is on Readme.

**Comment by guyellis** [comment]
@Raathigesh - just tested this on Ubuntu - works well - thanks! Closing.
