### ISSUE TITLE
Project fails to build on Workspace.ts

### ISSUE THREAD

**Issue by cuchi** [Raathigesh/majestic#42]
- Version of Majestic: 0.1.0
- Version of Node: 9.3.0
- Operating System: Debian Sid

Maybe I am doing something wrong, but this is what happens when I try to build the project:

### Steps to reproduce:
- Link `jest-editor-support` from jest
- Build majestic:
```bash
git clone git@github.com:Raathigesh/majestic.git
cd majestic
git checkout v0.1.0
yarn
yarn linux
```

Then the following errors occours:
```
paulo@debian [02:56:23 PM] [~/src/majestic] [8ae1152]
-> % yarn linux
yarn run v1.3.2
$ npm run compile && node_modules/.bin/build --linux

> majestic@0.1.0 compile /home/paulo/src/majestic
> electron-webpack

[1] Hash: 3a7fad97de5c77276a94607ec2b6f604ca46244a                                        
Version: webpack 3.8.1
Child
    Hash: 3a7fad97de5c77276a94
    Time: 40155ms
     2 assets
       [1] multi ./src/main/index.ts 28 bytes {0} [built]
       [2] ./src/main/index.ts + 1 modules 3.98 kB {0} [built]
        + 1 hidden module
    
    ERROR in /home/paulo/src/majestic/src/renderer/stores/Workspace.ts
    [tsl] ERROR in /home/paulo/src/majestic/src/renderer/stores/Workspace.ts(4,46)
          TS2307: Cannot find module './runner'.
    
    ERROR in /home/paulo/src/majestic/src/renderer/stores/Runner.ts
    [tsl] ERROR in /home/paulo/src/majestic/src/renderer/stores/Runner.ts(169,7)
          TS2554: Expected 1 arguments, but got 2.
    
    ERROR in /home/paulo/src/majestic/src/renderer/components/quick-search.tsx
    [tsl] ERROR in /home/paulo/src/majestic/src/renderer/components/quick-search.tsx(5,24)
          TS2307: Cannot find module 'classNames'.
Child
    Hash: 607ec2b6f604ca46244a
    Time: 52633ms
     11 assets
       [8] multi ./src/renderer/index.ts 28 bytes {0} [built]
       [9] ./src/renderer/index.ts + 26 modules 38 kB {0} [built]
      [11] ./src/renderer/stores/Workspace.ts 323 bytes {0} [built] [failed] [2 errors]
      [12] ./src/renderer/assets/logo.png 67 bytes {0} [built]
      [17] ./src/renderer/style.css 41 bytes {0} [built]
      [28] ./node_modules/css-loader!./src/renderer/style.css 1.82 kB [built]
        + 23 hidden modules
    
    ERROR in ./src/renderer/stores/Workspace.ts
    [tsl] ERROR in /home/paulo/src/majestic/src/renderer/stores/Workspace.ts(4,46)
          TS2307: Cannot find module './runner'.
    
    ERROR in /home/paulo/src/majestic/src/renderer/stores/Runner.ts
    [tsl] ERROR in /home/paulo/src/majestic/src/renderer/stores/Runner.ts(169,7)
          TS2554: Expected 1 arguments, but got 2.
    
    ERROR in ./src/renderer/components/quick-search.tsx
    [tsl] ERROR in /home/paulo/src/majestic/src/renderer/components/quick-search.tsx(5,24)
          TS2307: Cannot find module 'classNames'.
    
    ERROR in ./src/renderer/components/quick-search.tsx
    Module build failed: Error: Typescript emitted no output for /home/paulo/src/majestic/src/renderer/components/quick-search.tsx.
        at successLoader (/home/paulo/src/majestic/node_modules/ts-loader/dist/index.js:47:15)
        at Object.loader (/home/paulo/src/majestic/node_modules/ts-loader/dist/index.js:29:12)
     @ ./src/renderer/Container.tsx 8:0-52
     @ ./src/renderer/app.tsx
     @ ./src/renderer/index.ts
     @ multi ./src/renderer/index.ts
    
    ERROR in ./src/renderer/stores/Workspace.ts
    Module build failed: Error: Typescript emitted no output for /home/paulo/src/majestic/src/renderer/stores/Workspace.ts.
        at successLoader (/home/paulo/src/majestic/node_modules/ts-loader/dist/index.js:47:15)
        at Object.loader (/home/paulo/src/majestic/node_modules/ts-loader/dist/index.js:29:12)
     @ ./src/renderer/app.tsx 6:0-43
     @ ./src/renderer/index.ts
     @ multi ./src/renderer/index.ts
    Child html-webpack-plugin for "index.html":
         1 asset
           [0] ./node_modules/html-loader?minimize=false!/__virtual__/renderer-index.html 278 bytes {0} [built]
    Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!src/renderer/style.css:
           [0] ./node_modules/css-loader!./src/renderer/style.css 1.82 kB {0} [built]
            + 1 hidden module
    Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/@blueprintjs/core/dist/blueprint.css:
         6 assets
           8 modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! majestic@0.1.0 compile: `electron-webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the majestic@0.1.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paulo/.npm/_logs/2018-01-09T16_59_01_302Z-debug.log
error Command failed with exit code 2
```

This also happens on the master branch (other files, but `Cannot find module` errors too), is there something I am missing here 🤔 ?

**Comment by Raathigesh** [comment]
So there were few typescript errors I fixed on master so would you be able to try again. Also you can avoid doing a yarn link for now since the latest `jest-editor-support` is available on npm. 

But as I recall, there is an issue in the  `jest-editor-support`  module's type-definition file so you might have to edit that a bit.

**Comment by Raathigesh** [comment]
Hey @cuchi, The new alpha release support linux as well since we ship as an npm module. Keep to give it a try again?

**Comment by cuchi** [comment]
Just tested it. 
It is working seamlessly now!

Thanks!
