### ISSUE TITLE
[BUG] AssertionError

### ISSUE THREAD

**Issue by Neglexis** [Raathigesh/majestic#51]
This is a :bug:

## Version Info

- Version of Majestic: 0.2.0
- Version of Jest: 22.2.1
- Version of Node: v8.11.2
- Operating System: OS X

```
AssertionError {
  name: "AssertionError", 
  actual: "", 
  expected: true, 
  operator: "==", 
  message: "missing path"…
}
at Module.require (module.js:496:3)↵    at require (internal/module.js:20:19)↵    at a (file:///Applications/Majestic.app/Contents/Resources/app.asar/renderer.js:1:774)↵    at t.c (file:///Applications/Majestic.app/Contents/Resources/app.asar/renderer.js:1:1893)↵    at s (file:///Applications/Majestic.app/Contents/Resources/app.asar/renderer.js:1:4076)↵    at We.loadTestFiles (file:///Applications/Majestic.app/Contents/Resources/app.asar/renderer.js:3:7612)↵    at y.then (file:///Applications/Majestic.app/Contents/Resources/app.asar/renderer.js:3:8287)↵    at <anonymous>"__proto__: Error
```

**Comment by Neglexis** [comment]
Also tried this on the new alpha build, no success there either

```
Majestic v1.0.6
Zero config UI for Jest
visit http://localhost:3005
Killing the runner before exit
events.js:183
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: invalid status code 23982
    at Receiver.controlMessage (/usr/local/lib/node_modules/majestic/node_modules/ws/lib/receiver.js:441:18)
    at Receiver.getData (/usr/local/lib/node_modules/majestic/node_modules/ws/lib/receiver.js:329:42)
    at Receiver.startLoop (/usr/local/lib/node_modules/majestic/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/usr/local/lib/node_modules/majestic/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Receiver.Writable.write (_stream_writable.js:290:11)
    at Socket.socketOnData (/usr/local/lib/node_modules/majestic/node_modules/ws/lib/websocket.js:795:35)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
```

**Comment by Raathigesh** [comment]
Hey @Neglexis,

I published a new version of the new alpha build. Could you please try again and let me know if you run into any issues again?

**Comment by Neglexis** [comment]
@Raathigesh Appears to work, awesome! Looking good as well!

**Comment by Raathigesh** [comment]
Please feel free to report anything that needs to be looked into.
